//! Built-in plugin instantiation.
//!
//! Contains the canonical list of all built-in plugins, categorized by domain.

use super::super::{
    Plugin, adonis::AdonisPlugin, angular::AngularPlugin, astro::AstroPlugin, ava::AvaPlugin,
    babel::BabelPlugin, biome::BiomePlugin, browser_extension::BrowserExtensionPlugin,
    bun::BunPlugin, c8::C8Plugin, capacitor::CapacitorPlugin, changesets::ChangesetsPlugin,
    commitizen::CommitizenPlugin, commitlint::CommitlintPlugin,
    content_collections::ContentCollectionsPlugin, contentlayer::ContentlayerPlugin,
    convex::ConvexPlugin, cspell::CspellPlugin, cucumber::CucumberPlugin, cypress::CypressPlugin,
    danger::DangerPlugin, dependency_cruiser::DependencyCruiserPlugin,
    docusaurus::DocusaurusPlugin, drizzle::DrizzlePlugin, electron::ElectronPlugin,
    ember::EmberPlugin, eslint::EslintPlugin, expo::ExpoPlugin, expo_router::ExpoRouterPlugin,
    fumadocs::FumadocsPlugin, gatsby::GatsbyPlugin, graphql_codegen::GraphqlCodegenPlugin,
    hardhat::HardhatPlugin, husky::HuskyPlugin, i18next::I18nextPlugin, jest::JestPlugin,
    k6::K6Plugin, karma::KarmaPlugin, knex::KnexPlugin, kysely::KyselyPlugin,
    lefthook::LefthookPlugin, lexical::LexicalPlugin, lint_staged::LintStagedPlugin,
    lit::LitPlugin, markdownlint::MarkdownlintPlugin, mintlify::MintlifyPlugin, mocha::MochaPlugin,
    msw::MswPlugin, nestjs::NestJsPlugin, next_intl::NextIntlPlugin, nextjs::NextJsPlugin,
    nitro::NitroPlugin, nodemon::NodemonPlugin, nuxt::NuxtPlugin, nx::NxPlugin, nyc::NycPlugin,
    obsidian::ObsidianPlugin, openapi_ts::OpenapiTsPlugin, opencode::OpenCodePlugin,
    opennext_cloudflare::OpenNextCloudflarePlugin, oxlint::OxlintPlugin, pandacss::PandaCssPlugin,
    parcel::ParcelPlugin, pkg_utils::PkgUtilsPlugin, playwright::PlaywrightPlugin,
    plop::PlopPlugin, pm2::Pm2Plugin, pnpm::PnpmPlugin, postcss::PostCssPlugin,
    prettier::PrettierPlugin, prisma::PrismaPlugin, qwik::QwikPlugin,
    react_native::ReactNativePlugin, react_router::ReactRouterPlugin, redwoodsdk::RedwoodSdkPlugin,
    relay::RelayPlugin, remark::RemarkPlugin, remix::RemixPlugin, rolldown::RolldownPlugin,
    rollup::RollupPlugin, rsbuild::RsbuildPlugin, rspack::RspackPlugin, rspress::RspressPlugin,
    sanity::SanityPlugin, semantic_release::SemanticReleasePlugin, sentry::SentryPlugin,
    simple_git_hooks::SimpleGitHooksPlugin, storybook::StorybookPlugin, stryker::StrykerPlugin,
    stylelint::StylelintPlugin, supabase::SupabasePlugin, sveltekit::SvelteKitPlugin,
    svgo::SvgoPlugin, svgr::SvgrPlugin, swc::SwcPlugin, syncpack::SyncpackPlugin,
    tailwind::TailwindPlugin, tanstack_router::TanstackRouterPlugin, tap::TapPlugin,
    tsd::TsdPlugin, tsdown::TsdownPlugin, tsup::TsupPlugin, turborepo::TurborepoPlugin,
    typedoc::TypedocPlugin, typeorm::TypeormPlugin, typescript::TypeScriptPlugin,
    unocss::UnoCssPlugin, varlock::VarlockPlugin, velite::VelitePlugin, vite::VitePlugin,
    vitepress::VitePressPlugin, vitest::VitestPlugin, webdriverio::WebdriverioPlugin,
    webpack::WebpackPlugin, wrangler::WranglerPlugin, wuchale::WuchalePlugin, wxt::WxtPlugin,
};

/// Create all built-in plugin instances, categorized by domain.
pub fn create_builtin_plugins() -> Vec<Box<dyn Plugin>> {
    vec![
        // Frameworks
        Box::new(NextJsPlugin),
        Box::new(NuxtPlugin),
        Box::new(RemixPlugin),
        Box::new(AstroPlugin),
        Box::new(BrowserExtensionPlugin),
        Box::new(WxtPlugin),
        Box::new(AngularPlugin),
        Box::new(ReactRouterPlugin),
        Box::new(RedwoodSdkPlugin),
        Box::new(TanstackRouterPlugin),
        Box::new(ReactNativePlugin),
        Box::new(ExpoPlugin),
        Box::new(ExpoRouterPlugin),
        Box::new(NestJsPlugin),
        Box::new(AdonisPlugin),
        Box::new(DocusaurusPlugin),
        Box::new(GatsbyPlugin),
        Box::new(SvelteKitPlugin),
        Box::new(NitroPlugin),
        Box::new(CapacitorPlugin),
        Box::new(SanityPlugin),
        Box::new(SupabasePlugin),
        Box::new(VitePressPlugin),
        Box::new(RspressPlugin),
        Box::new(NextIntlPlugin),
        Box::new(RelayPlugin),
        Box::new(ElectronPlugin),
        Box::new(I18nextPlugin),
        Box::new(QwikPlugin),
        Box::new(ConvexPlugin),
        Box::new(LitPlugin),
        Box::new(LexicalPlugin),
        Box::new(ObsidianPlugin),
        Box::new(ContentCollectionsPlugin),
        Box::new(ContentlayerPlugin),
        Box::new(FumadocsPlugin),
        Box::new(MintlifyPlugin),
        Box::new(VelitePlugin),
        Box::new(EmberPlugin),
        // Bundlers
        Box::new(VitePlugin),
        Box::new(WebpackPlugin),
        Box::new(RollupPlugin),
        Box::new(RolldownPlugin),
        Box::new(RspackPlugin),
        Box::new(RsbuildPlugin),
        Box::new(TsupPlugin),
        Box::new(TsdownPlugin),
        Box::new(PkgUtilsPlugin),
        Box::new(ParcelPlugin),
        // Testing
        Box::new(VitestPlugin),
        Box::new(JestPlugin),
        Box::new(PlaywrightPlugin),
        Box::new(CypressPlugin),
        Box::new(MochaPlugin),
        Box::new(AvaPlugin),
        Box::new(TapPlugin),
        Box::new(TsdPlugin),
        Box::new(K6Plugin),
        Box::new(StorybookPlugin),
        Box::new(StrykerPlugin),
        Box::new(KarmaPlugin),
        Box::new(CucumberPlugin),
        Box::new(WebdriverioPlugin),
        // Linting & formatting
        Box::new(EslintPlugin),
        Box::new(BiomePlugin),
        Box::new(StylelintPlugin),
        Box::new(PrettierPlugin),
        Box::new(OxlintPlugin),
        Box::new(MarkdownlintPlugin),
        Box::new(CspellPlugin),
        Box::new(RemarkPlugin),
        // Transpilation & language
        Box::new(TypeScriptPlugin),
        Box::new(BabelPlugin),
        Box::new(SwcPlugin),
        // CSS
        Box::new(TailwindPlugin),
        Box::new(PostCssPlugin),
        Box::new(UnoCssPlugin),
        Box::new(PandaCssPlugin),
        // Database & ORM
        Box::new(PrismaPlugin),
        Box::new(DrizzlePlugin),
        Box::new(KnexPlugin),
        Box::new(TypeormPlugin),
        Box::new(KyselyPlugin),
        // Monorepo
        Box::new(TurborepoPlugin),
        Box::new(NxPlugin),
        Box::new(ChangesetsPlugin),
        Box::new(SyncpackPlugin),
        // CI/CD & release
        Box::new(CommitlintPlugin),
        Box::new(CommitizenPlugin),
        Box::new(SemanticReleasePlugin),
        Box::new(DangerPlugin),
        // Blockchain
        Box::new(HardhatPlugin),
        // Deployment
        Box::new(WranglerPlugin),
        Box::new(OpenNextCloudflarePlugin),
        Box::new(SentryPlugin),
        // Git hooks
        Box::new(HuskyPlugin),
        Box::new(LintStagedPlugin),
        Box::new(LefthookPlugin),
        Box::new(SimpleGitHooksPlugin),
        // Media & assets
        Box::new(SvgoPlugin),
        Box::new(SvgrPlugin),
        // Code generation & docs
        Box::new(GraphqlCodegenPlugin),
        Box::new(TypedocPlugin),
        Box::new(OpenapiTsPlugin),
        Box::new(PlopPlugin),
        // Coverage
        Box::new(C8Plugin),
        Box::new(NycPlugin),
        // Other tools
        Box::new(MswPlugin),
        Box::new(OpenCodePlugin),
        Box::new(NodemonPlugin),
        Box::new(Pm2Plugin),
        Box::new(DependencyCruiserPlugin),
        Box::new(WuchalePlugin),
        Box::new(VarlockPlugin),
        // Package managers
        Box::new(PnpmPlugin),
        // Runtime
        Box::new(BunPlugin),
    ]
}
