/**
 * Generate the shared TypeScript output contract from `docs/output-schema.json`.
 *
 * Writes the same `.d.ts` to two locations atomically:
 *   - editors/vscode/src/generated/output-contract.d.ts (consumed by the extension)
 *   - npm/fallow/types/output-contract.d.ts (published via `fallow/types` subpath)
 *
 * Both are committed to git. `--check` mode regenerates and diffs against both
 * files; CI fails if either drifts.
 *
 * Run: `pnpm --filter fallow-vscode codegen:types`
 *      `pnpm --filter fallow-vscode check:codegen`
 */
import { compile } from "json-schema-to-typescript";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const EXTENSION_ROOT = resolve(SCRIPT_DIR, "..");
const REPO_ROOT = resolve(EXTENSION_ROOT, "..", "..");
const SCHEMA_PATH = resolve(REPO_ROOT, "docs", "output-schema.json");
const SCHEMA_VERSION_SOURCE = resolve(
  REPO_ROOT,
  "crates",
  "cli",
  "src",
  "report",
  "json.rs",
);
const OUT_PATHS = [
  resolve(EXTENSION_ROOT, "src", "generated", "output-contract.d.ts"),
  resolve(REPO_ROOT, "npm", "fallow", "types", "output-contract.d.ts"),
];

const BANNER = `/**
 * AUTOGENERATED FILE. DO NOT EDIT.
 *
 * Generated from \`docs/output-schema.json\` by
 * \`editors/vscode/scripts/codegen-types.mjs\`. The same file is written to
 * \`editors/vscode/src/generated/output-contract.d.ts\` (extension internal) and
 * \`npm/fallow/types/output-contract.d.ts\` (published as \`fallow/types\`).
 *
 * To change a shape:
 *   1. Edit the Rust struct in \`crates/types/src/results.rs\` (or the
 *      duplicates crate at \`crates/core/src/duplicates/types.rs\`). The Rust
 *      side is the runtime source of truth for the JSON output.
 *   2. Update \`docs/output-schema.json\` to match. The schema is
 *      hand-maintained against the Rust structs; the drift-guard test in
 *      \`crates/cli/src/report/json.rs\` enforces only a subset of the
 *      contract (the \`HealthFindingAction\` enum). Field-level drift between
 *      Rust and the schema is currently caught by code review.
 *   3. Run \`pnpm --filter fallow-vscode codegen:types\` from anywhere.
 *   4. Commit both regenerated files alongside the schema edit.
 *
 * CI runs \`pnpm --filter fallow-vscode check:codegen\` which fails when
 * either committed file disagrees with what regen would produce.
 */
/* eslint-disable */
`;

const OPTIONS = {
  // Default for objects whose schema does not declare additionalProperties.
  // The schema is intentionally permissive at validation time (forward-compat
  // for JSON validators on older fallow versions), but for the TypeScript
  // contract we want closed shapes: missing-field reads should be a compile
  // error, not silent `unknown`.
  additionalProperties: false,
  bannerComment: BANNER,
  // Skip prettier formatting. jstt's raw output is stable across invocations,
  // which keeps the drift-check diff trivial. The committed file is read-only
  // for humans anyway.
  format: false,
  // Use `unknown` rather than `any` for the rare cases the schema admits it.
  unknownAny: true,
  // Include all named definitions, including helpers like SchemaVersion that
  // are referenced via $ref but not directly under the root oneOf.
  unreachableDefinitions: true,
  // Use the file path itself for ref resolution.
  cwd: REPO_ROOT,
};

/**
 * Strip `title` (and the root `$id`) from the schema before generation.
 * jstt prefers `title` over the definition key (or the explicit name argument
 * passed to `compile`) when naming generated types: documentary titles like
 * "fallow dead-code --format json" otherwise become mangled names like
 * `FallowDeadCodeFormatJson` (plus a duplicate `CheckOutput`), and the root
 * title "Fallow JSON Output Schemas" otherwise becomes `FallowJSONOutputSchemas`
 * regardless of the second argument to `compile`.
 *
 * `$id` has the same problem: when the root carries
 * `https://raw.githubusercontent.com/.../output-schema.json`, jstt mangles it
 * into `HttpsRawGithubusercontentComFallowRsFallowMainDocsOutputSchemaJson`.
 * The published schema needs `$id` for consumer SHA-pinning, but the TS
 * generation does not, so strip it here. `$comment` is documentary and ignored
 * by jstt; left in place.
 *
 * We keep `description` (used as JSDoc) and only drop `title` plus the root
 * `$id` (TS naming).
 */
function stripTitles(schema) {
  if ("title" in schema) {
    delete schema.title;
  }
  if ("$id" in schema) {
    delete schema.$id;
  }
  if (schema.definitions) {
    for (const def of Object.values(schema.definitions)) {
      if (def && typeof def === "object" && "title" in def) {
        delete def.title;
      }
    }
  }
  return schema;
}

/**
 * Walk the schema and remove sibling keys next to `$ref`. JSON Schema Draft 07
 * specifies that `$ref` siblings are ignored at validation time, but jstt
 * treats `{ "$ref": "...", "description": "..." }` as an inline schema and
 * generates a duplicate type rather than emitting a plain alias. Stripping
 * the `description` (and any other sibling) at codegen time keeps generated
 * names canonical without losing the documentation in the source schema.
 */
function flattenRefSiblings(node) {
  if (!node || typeof node !== "object") return node;
  if (Array.isArray(node)) {
    for (const item of node) flattenRefSiblings(item);
    return node;
  }
  if (typeof node.$ref === "string") {
    for (const key of Object.keys(node)) {
      if (key !== "$ref") delete node[key];
    }
    return node;
  }
  for (const value of Object.values(node)) flattenRefSiblings(value);
  return node;
}

/**
 * Read `const SCHEMA_VERSION: u32 = N;` from the canonical Rust source so the
 * generated TS pins `SchemaVersion` to the literal N (not bare `number`).
 *
 * Pinning lets downstream consumers gate on the schema version with a literal
 * type comparison: a major bump that changes the constant in Rust produces a
 * compile error at every call site that branches on the old literal, instead
 * of silently drifting.
 */
async function readRustSchemaVersion() {
  const source = await readFile(SCHEMA_VERSION_SOURCE, "utf8");
  const match = source.match(/const\s+SCHEMA_VERSION:\s*u32\s*=\s*(\d+)\s*;/);
  if (!match) {
    throw new Error(
      `Could not find \`const SCHEMA_VERSION: u32 = N;\` in ${SCHEMA_VERSION_SOURCE}`,
    );
  }
  return Number(match[1]);
}

/**
 * Post-process jstt's output to replace the bare `number` alias for
 * `SchemaVersion` with the literal pulled from Rust.
 *
 * Throws if the bare alias is missing: that would mean either jstt changed its
 * emission shape or the schema's SchemaVersion definition changed; either way
 * the pin is no longer reliable and the build should fail loudly.
 */
function pinSchemaVersion(contents, version) {
  const target = "export type SchemaVersion = number";
  if (!contents.includes(target)) {
    throw new Error(
      `pinSchemaVersion: expected to find \`${target}\` in generated output. ` +
        "Did jstt's emission change, or is `SchemaVersion` no longer a top-level " +
        "definition in docs/output-schema.json?",
    );
  }
  return contents.replace(target, `export type SchemaVersion = ${version}`);
}

/**
 * Strip trailing whitespace from each line. jstt's JSDoc renderer emits
 * paragraph breaks as `   * ` (asterisk + space + EOL), which trips
 * `git diff --check`'s whitespace gate and CI's repo-hygiene lint. The
 * downstream type semantics are unchanged.
 */
function stripTrailingWhitespace(contents) {
  return contents.replace(/[ \t]+$/gm, "");
}

async function generate() {
  const raw = await readFile(SCHEMA_PATH, "utf8");
  const parsed = JSON.parse(raw);
  stripTitles(parsed);
  flattenRefSiblings(parsed);
  // With the root title stripped, jstt uses the second arg as the name of the
  // top-level union type.
  const raw_ts = await compile(parsed, "FallowJsonOutput", OPTIONS);
  const version = await readRustSchemaVersion();
  return stripTrailingWhitespace(pinSchemaVersion(raw_ts, version));
}

async function writeAll(contents) {
  for (const path of OUT_PATHS) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, "utf8");
  }
}

async function check() {
  const generated = await generate();
  const stale = [];
  for (const path of OUT_PATHS) {
    const committed = await readFile(path, "utf8").catch(() => "");
    if (committed !== generated) {
      stale.push(path);
    }
  }
  if (stale.length === 0) {
    return 0;
  }
  process.stderr.write(
    "\x1b[31mcheck:codegen FAILED\x1b[0m: the following generated files " +
      "are out of date with `docs/output-schema.json`:\n",
  );
  for (const path of stale) {
    process.stderr.write(`  - ${path}\n`);
  }
  process.stderr.write(
    "Run `pnpm --filter fallow-vscode codegen:types` and commit the result.\n",
  );
  return 1;
}

const mode = process.argv[2];
if (mode === "--check") {
  const code = await check();
  process.exit(code);
} else {
  const contents = await generate();
  await writeAll(contents);
  for (const path of OUT_PATHS) {
    process.stdout.write(`Wrote ${path}\n`);
  }
}
